export const products = {
  technology: [
    {
      id: 1,
      name: "MacBook Air M2",
      price: 8999.99,
      image: "",
      description:
        "Notebook ultraleve e elegante da Apple, equipado com o chip M2 de última geração. Perfeito para tarefas do dia a dia, edição de fotos, vídeos e produtividade intensa, tudo com eficiência energética surpreendente. Seu design silencioso e compacto o torna ideal para quem busca desempenho e portabilidade sem abrir mão do estilo.",
      specs: {
        processor: "Apple M2",
        ram: "8GB",
        storage: "256GB SSD",
        display: "13.6'' Liquid Retina",
        battery: "18 horas",
        weight: "1,24 kg",
        operating_system: "macOS",
      },
    },
    {
      id: 2,
      name: "Logitech MX Master 3S",
      price: 549.9,
      image: "",
      description:
        "Um dos mouses mais amados pelos profissionais criativos e desenvolvedores. O MX Master 3S combina ergonomia impecável com precisão extrema, graças ao sensor de 8000 DPI. Com rolagem eletromagnética silenciosa, botões personalizáveis e longa duração de bateria, é a escolha definitiva para conforto e produtividade em qualquer ambiente.",
      specs: {
        connectivity: "Bluetooth / Receptor USB",
        dpi: "8000 DPI",
        buttons: "7 botões personalizáveis",
        battery: "70 dias",
        compatibility: "Windows / macOS / Linux",
        weight: "141 g",
        color: "Grafite",
      },
    },
    {
      id: 3,
      name: "Google Pixel 8 Pro",
      price: 6999.0,
      image: "",
      description:
        "Smartphone topo de linha com foco em inteligência artificial e fotografia profissional. Equipado com o processador Google Tensor G3, ele traz uma experiência fluida e inteligente no Android 14. Com câmera tripla de altíssima qualidade e tela OLED de 6.7’’ com 120Hz, é perfeito para quem busca inovação, desempenho e fotos impressionantes.",
      specs: {
        processor: "Google Tensor G3",
        ram: "12GB",
        storage: "256GB",
        camera: "50MP + 48MP + 48MP",
        display: "6.7'' OLED 120Hz",
        battery: "5050 mAh",
        operating_system: "Android 14",
      },
    },
    {
      id: 4,
      name: "SSD Samsung T7 Shield",
      price: 699.0,
      image: "",
      description:
        "Um SSD portátil projetado para quem precisa de velocidade e durabilidade. Com resistência a choques e água, o T7 Shield oferece segurança mesmo em ambientes adversos. Ideal para profissionais que transportam arquivos grandes, como vídeos em 4K, mantendo desempenho de até 1050 MB/s e design compacto para o dia a dia.",
      specs: {
        capacity: "1TB",
        interface: "USB 3.2 Gen 2",
        speed: "Até 1050 MB/s",
        compatibility: "Windows / macOS / Android",
        protection: "Resistente a choque e água",
        color: "Preto",
        weight: "98 g",
      },
    },
    {
      id: 5,
      name: "Razer BlackShark V2",
      price: 599.9,
      image: "",
      description:
        "Headset gamer de alta performance, pensado para entregar imersão total em jogos e chamadas. Com drivers de 50mm e tecnologia THX Spatial Audio, proporciona som tridimensional realista. O microfone destacável e o design leve garantem conforto prolongado em sessões intensas, seja no PC, console ou celular.",
      specs: {
        connectivity: "Com fio (3.5mm)",
        drivers: "50mm Razer TriForce",
        microphone: "Cardioide destacável",
        compatibility: "PC / Console / Mobile",
        cable_length: "1,8 m",
        weight: "262 g",
        color: "Preto/Verde",
      },
    },
    {
      id: 6,
      name: "Placa de Vídeo ASUS ROG Strix RTX 4070",
      price: 4899.99,
      image: "",
      description:
        "Placa gráfica premium para quem exige o máximo em jogos, edição de vídeo e renderização 3D. Com arquitetura Ada Lovelace da NVIDIA e 12GB de memória GDDR6X, ela entrega gráficos realistas com ray tracing e DLSS 3. O sistema de refrigeração com três ventoinhas mantém tudo estável e silencioso, mesmo sob carga pesada.",
      specs: {
        chipset: "NVIDIA GeForce RTX 4070",
        memory: "12GB GDDR6X",
        interface: "PCIe 4.0",
        cooling: "Triple-fan",
        outputs: "HDMI 2.1, DisplayPort 1.4a",
        power_draw: "Fonte recomendada de 650W",
      },
    },
    {
      id: 7,
      name: "Elgato Stream Deck MK.2",
      price: 999.0,
      image: "",
      description:
        "Ferramenta essencial para streamers, editores e criadores de conteúdo. Com 15 teclas LCD totalmente personalizáveis, o Stream Deck oferece acesso rápido a comandos, macros e integrações com software como OBS, Photoshop, Spotify e muito mais. Tudo isso com design modular, conexão USB-C e interface intuitiva de arrastar e soltar.",
      specs: {
        keys: "15 teclas LCD",
        connectivity: "USB-C",
        compatibility: "Windows / macOS",
        customization: "Interface de arrastar e soltar",
        material: "Plástico com faceplate magnético",
        weight: "270 g",
      },
    },
    {
      id: 8,
      name: "Sony WH-1000XM5",
      price: 1999.9,
      image: "",
      description:
        "Fones de ouvido sem fio com cancelamento de ruído ativo de última geração. O WH-1000XM5 oferece qualidade sonora premium, conforto absoluto para uso prolongado e autonomia de até 30 horas. Ideal para viagens, trabalho e momentos de relaxamento, com carregamento rápido e controle inteligente por toque e voz.",
      specs: {
        connectivity: "Bluetooth 5.2",
        noise_cancellation: "Ativo",
        battery: "Até 30 horas",
        drivers: "30mm",
        fast_charging: "3 min = 3h de reprodução",
        weight: "250 g",
        color: "Preto",
      },
    },
    {
      id: 9,
      name: "Carregador Anker 737 GaNPrime",
      price: 399.0,
      image: "",
      description:
        "Um dos carregadores mais avançados do mercado, com 120W de potência e tecnologia GaN que oferece carregamento eficiente e seguro. Com três portas (2x USB-C + 1x USB-A), é perfeito para alimentar notebooks, celulares e tablets ao mesmo tempo. Compacto, robusto e pronto para acompanhar você em qualquer lugar.",
      specs: {
        ports: "2x USB-C, 1x USB-A",
        output_power: "120W máx",
        compatibility: "Celulares / Tablets / Notebooks",
        technology: "GaN (Nitreto de Gálio)",
        dimensions: "6,7 x 3,6 x 4,2 cm",
        weight: "195 g",
      },
    },
    {
      id: 10,
      name: "Sensor de Porta Inteligente Aqara",
      price: 129.0,
      image: "",
      description:
        "Dispositivo compacto e eficiente para automação residencial. Detecta abertura e fechamento de portas ou janelas e se integra com Apple HomeKit, Alexa e Google Assistant via Zigbee. Ideal para alertas de segurança e rotinas automatizadas, com fácil instalação por adesivo e bateria que dura até 2 anos.",
      specs: {
        connectivity: "Zigbee 3.0",
        battery: "CR2032 (2 anos)",
        range: "Detecção até 22mm",
        compatibility: "HomeKit / Alexa / Google",
        mounting: "Adesivo",
        material: "Plástico ABS",
      },
    },
  ],
  clothes: [
    {
      id: 11,
      name: "Camiseta Oversized",
      price: 89.9,
      image: "",
      description:
        "Camiseta oversized super estilosa e confortável, feita com tecido 100% algodão que é macio ao toque e respirável. Perfeita para quem ama looks despojados e modernos, com caimento mais solto que abraça seu corpo com leveza e atitude. Ideal pra compor desde o streetwear até aquele outfit comfy de ficar em casa.",
      specs: {
        material: "100% Algodão",
        fit: "Oversized",
        sleeve_length: "Manga Curta",
        color: "Branca",
        gender: "Unissex",
        size_range: "P ao GG",
      },
    },
    {
      id: 12,
      name: "Jaqueta Jeans Vintage",
      price: 219.9,
      image: "",
      description:
        "Jaqueta jeans com vibe retrô irresistível, trazendo aquela lavagem vintage que nunca sai de moda. Com costura reforçada e corte clássico, ela combina perfeitamente com qualquer look casual. Ideal para sobrepor em dias fresquinhos e arrasar no estilo com atitude e personalidade.",
      specs: {
        material: "100% Algodão Jeans",
        closure: "Botão",
        pockets: "2 Bolsos no Peito, 2 Laterais",
        color: "Azul",
        fit: "Regular",
        lining: "Sem forro",
      },
    },
    {
      id: 13,
      name: "Moletom Canguru com Capuz",
      price: 149.9,
      image: "",
      description:
        "Moletom quentinho e gostoso com estilo descolado. Possui capuz ajustável com cordão e bolso canguru frontal que é perfeito pra aquecer as mãozinhas ou guardar suas coisinhas. Ideal pra usar em dias frios com muito conforto e aquele toque casual que todo mundo ama.",
      specs: {
        material: "Mistura de Algodão/Poliéster",
        style: "Casual",
        hood: "Sim",
        pocket: "Bolso Canguru Frontal",
        sleeve_length: "Manga Longa",
        colors: "Preto, Cinza",
      },
    },
    {
      id: 14,
      name: "Calça Jogger Preta",
      price: 129.0,
      image: "",
      description:
        "Jogger preta versátil e cheia de atitude, feita com tecido confortável que acompanha seus movimentos com estilo. O cós elástico com cordão garante ajuste perfeito na cintura e os punhos elásticos nas pernas dão aquele caimento moderninho. Ideal pra montar um look urbano ou esportivo.",
      specs: {
        material: "Algodão/Poliéster",
        waistband: "Elástico com cordão",
        pockets: "2 Bolsos Laterais",
        color: "Preta",
        fit: "Modelagem Slim",
        ankle: "Punhos Elásticos",
      },
    },
    {
      id: 15,
      name: "Vestido Floral Midi",
      price: 189.9,
      image: "",
      description:
        "Vestido midi romântico e leve como uma brisa. Com estampa floral delicada e corte evasê, ele valoriza a silhueta com elegância e movimento. Perfeito para ocasiões especiais ou dias em que você quer se sentir ainda mais linda, soltinha e feminina.",
      specs: {
        material: "Viscose (Rayon)",
        length: "Midi",
        neckline: "Decote V",
        pattern: "Floral",
        sleeve_length: "Manga Curta",
        fit: "Evasê",
      },
    },
    {
      id: 16,
      name: "Blusa Canelada de Manga Longa",
      price: 69.9,
      image: "",
      description:
        "Blusa justinha com textura canelada que modela o corpo com sutileza. Com manga longa e gola redonda, ela é perfeita pra montar desde looks básicos até composições mais elegantes. Um toque confortável, macio e sensual pro seu dia a dia.",
      specs: {
        material: "Mistura de Algodão Canelado",
        sleeve_length: "Manga Longa",
        neckline: "Gola Redonda",
        fit: "Justa",
        color: "Bege, Preta",
        stretch: "Sim",
      },
    },
    {
      id: 17,
      name: "Saia Plissada Rosa",
      price: 119.9,
      image: "",
      description:
        "Saia midi super charmosa com plissado delicado e caimento fluido. O rosa clarinho dá um ar romântico e elegante, enquanto a cintura alta valoriza as curvas com sutileza. Ideal pra criar looks femininos e modernos com um toque de princesa.",
      specs: {
        material: "Poliéster",
        length: "Midi",
        waist: "Cintura Alta",
        color: "Rosa Claro",
        closure: "Zíper",
        lining: "Sim",
      },
    },
    {
      id: 18,
      name: "Camisa Social Slim",
      price: 139.9,
      image: "",
      description:
        "Camisa social clássica com corte slim que se ajusta ao corpo com elegância. Perfeita para compor looks formais ou casuais chiques, com tecido confortável e gola italiana sofisticada. Ideal pra quem gosta de estar bem-vestido sem abrir mão do conforto.",
      specs: {
        material: "Mistura de Algodão",
        fit: "Modelagem Slim",
        collar: "Gola Italiana",
        sleeve_length: "Manga Longa",
        cuffs: "Com Botões",
        colors: "Branca, Azul Claro",
      },
    },
    {
      id: 19,
      name: "Top Fitness Cropped",
      price: 59.9,
      image: "",
      description:
        "Top esportivo cropped com tecido respirável e toque suave. Com suporte médio e bojo removível, ele te acompanha nos treinos com conforto e segurança, além de realçar a silhueta com um caimento incrível. Um must-have pra arrasar na academia ou no look fitness casual.",
      specs: {
        material: "Poliamida/Elastano",
        support_level: "Médio",
        straps: "Alças Fixas",
        color: "Lilás, Preto",
        padding: "Removível",
        fit: "Justo",
      },
    },
    {
      id: 20,
      name: "Shorts Jeans Destroyed",
      price: 99.9,
      image: "",
      description:
        "Short jeans com aquele acabamento destroyed que dá um ar rebelde e sensual. Lavagem clara, corte curtinho e modelagem soltinha deixam as pernas à mostra com muito estilo. Ideal pra dias quentes, rolês de verão ou só pra se sentir uma gata poderosa.",
      specs: {
        material: "100% Algodão Jeans",
        fit: "Solto",
        length: "Curto",
        waist: "Cintura Média",
        closure: "Botão e Zíper",
        style: "Desgastado / Lavado",
      },
    },
  ],
};
